#%RAML 1.0
title: SQL-System-API
description: This project is based on SQL-Basic-END Points
traits:
  Get-props: !include traits/get_method.raml
  Get-response: !include traits/get_response.raml
  client-id-required: !include traits/client_id_enforcement.raml
/{table}:
    is: [Get-props,client-id-required]
    uriParameters:
      table: 
        type : string
        description: "table name for sql query will be filled from here"
    get:
      description: to get records from database based on inputs
      is : [Get-response]
    post: 
      description: To Insert Records into Database
      queryParameters:
        Fields:
          type: string
          pattern: ^(.+)(,(.+))*$
          description: Fields to Insert into Database Table
      body:
        application/json:
          type: array
          items: object
          example: 
      responses:
        201:
          body:
            application/json:
              example:
                { 
                  message : "Records Inserted Successsfully"}
      
        